# 城市名稱對照表
CITY_NAMES = {
    # 國際城市
    # 日本
    "東京": "Tokyo",
    "東京都": "Tokyo",
    "大阪": "Osaka",
    "大阪市": "Osaka",
    "京都": "Kyoto",
    "京都市": "Kyoto",
    "名古屋": "Nagoya",
    "福岡": "Fukuoka",
    "札幌": "Sapporo",
    "沖繩": "Okinawa",
    "那霸": "Naha",
    # 美國
    "紐約": "New York",
    "紐約市": "New York",
    "洛杉磯": "Los Angeles",
    "舊金山": "San Francisco",
    "西雅圖": "Seattle",
    "華盛頓": "Washington",
    "華盛頓特區": "Washington, DC",
    "華府": "Washington, DC",
    "芝加哥": "Chicago",
    "波士頓": "Boston",
    # 韓國
    "首爾": "Seoul",
    "釜山": "Busan",
    # 中國
    "北京": "Beijing",
    "上海": "Shanghai",
    "廣州": "Guangzhou",
    "深圳": "Shenzhen",
    "香港": "Hong Kong",
    "澳門": "Macau",
    # 新加坡
    "新加坡": "Singapore",
    # 英國
    "倫敦": "London",
    # 法國
    "巴黎": "Paris",
    # 德國
    "柏林": "Berlin",
    # 義大利
    "羅馬": "Rome",
    "米蘭": "Milan",
    # 澳洲
    "雪梨": "Sydney",
    "墨爾本": "Melbourne",
    
    # 台灣城市
    "臺北": "Taipei City",
    "台北": "Taipei City",
    "臺北市": "Taipei City",
    "台北市": "Taipei City",
    "新北": "New Taipei City",
    "新北市": "New Taipei City",
    "桃園": "Taoyuan City",
    "桃園市": "Taoyuan City",
    "臺中": "Taichung City",
    "台中": "Taichung City",
    "臺中市": "Taichung City",
    "台中市": "Taichung City",
    "臺南": "Tainan City",
    "台南": "Tainan City",
    "臺南市": "Tainan City",
    "台南市": "Tainan City",
    "高雄": "Kaohsiung City",
    "高雄市": "Kaohsiung City",
    # 省轄市
    "基隆": "Keelung City",
    "基隆市": "Keelung City",
    "新竹": "Hsinchu City",
    "新竹市": "Hsinchu City",
    "嘉義": "Chiayi City",
    "嘉義市": "Chiayi City",
    # 縣
    "新竹縣": "Hsinchu County",
    "苗栗": "Miaoli County",
    "苗栗縣": "Miaoli County",
    "彰化": "Changhua County",
    "彰化縣": "Changhua County",
    "南投": "Nantou County",
    "南投縣": "Nantou County",
    "雲林": "Yunlin County",
    "雲林縣": "Yunlin County",
    "嘉義縣": "Chiayi County",
    "屏東": "Pingtung County",
    "屏東縣": "Pingtung County",
    "宜蘭": "Yilan County",
    "宜蘭縣": "Yilan County",
    "花蓮": "Hualien County",
    "花蓮縣": "Hualien County",
    "臺東": "Taitung County",
    "台東": "Taitung County",
    "臺東縣": "Taitung County",
    "台東縣": "Taitung County",
    "澎湖": "Penghu County",
    "澎湖縣": "Penghu County",
    "金門": "Kinmen County",
    "金門縣": "Kinmen County",
    "連江": "Lienchiang County",
    "連江縣": "Lienchiang County",
    "馬祖": "Lienchiang County"
}
